### ISSUE TITLE
error: fvar option ...

### ISSUE THREAD

**Issue by rbarbone** [sergiocorreia/reghdfe#63] opened 2016-08-09 02:35 UTC
Dear Sergio, 

Thank you for the great work and website...reghdfe is an incredible tool! 

I run into this issue though...and .I couldnt find anything in statalist of the FAQs of your site. 

I am running the following regression...

```
reghdfe $dep $treat_alt $controls_1 $controls_3 , absorb(firm_id#time_id bank_id) vce(cluster bank_id time_id)
```

and I run into this error message...."option fvwrap() not allowed"

I can run   reghdfe $dep $treat_alt $controls_1 $controls_3 , absorb(firm_id#time_id bank_id) vce(cluster bank_id#time_id),  but not the double clustering. I also tried with other variables... 

I used the command group() to create both bank_id and time_id

The example in your webpage works smoothly by the way.

**Comment by sergiocorreia** [comment] 2016-08-09 13:03
It's a bit hard to debug the problem with the info at hand, but this would help:

- Could you post the content of the global macros?
- Also, run reghdfe with the `verbose(3)` option
- Finally, run `set trace on` beforehand (and possibly `set tracedepth 4`) and then paste the log

Finally, if this is because of a bug in the cluster computation, using the avar suite would help:
 
```
ssc install avar
reghdfe price weight, a(turn#trunk foreign) vce(cluster foreign trunk, suite(avar))
```

(Notice the -suite- suboption)

**Comment by sergiocorreia** [comment] 2016-08-09 13:04
Also possibly related:

http://www.stata.com/statalist/archive/2013-09/msg00368.html

**Comment by sergiocorreia** [comment] 2017-02-15 00:06
Closed as I cannot reproduce it

**Closed by sergiocorreia** 2017-02-15 00:06 UTC
