### ISSUE TITLE
F statistics vary from run to run, whereas areg reports them as missing

### ISSUE THREAD

**Issue by NilsEnevoldsen** [sergiocorreia/reghdfe#13] opened 2015-05-13 21:29 UTC
```stata
clear
input x1	x2	x3	x4	x5	y	fe	clustervar
0	1	0	1	0	0	1	18
0	1	0	1	1	0	1	18
0	1	1	0	0	0	2	18
0	1	1	0	1	0	2	18
1	1	0	1	0	0	3	18
1	1	0	1	1	0	3	18
0	0	0	1	0	53.08017	4	18
0	0	0	1	1	18.87388	4	18
0	1	0	1	0	0	5	19
0	1	0	1	1	0	5	19
1	1	1	0	0	0	6	18
1	1	1	0	1	0	6	18
0	1	0	0	0	0	7	18
0	1	0	0	1	0	7	18
0	0	0	0	0	30.93297	8	18
0	0	0	0	1	.8479494	8	18
1	1	1	0	0	116.4302	9	15
1	1	1	0	1	0	9	15
0	0	0	1	0	0	10	15
0	0	0	1	1	0	10	15
0	1	0	1	0	0	11	15
0	1	0	1	1	0	11	15
0	0	1	0	0	140.2202	12	14
0	0	1	0	1	49.51491	12	14
1	1	1	0	0	0	13	15
1	1	1	0	1	0	13	15
0	1	0	0	0	0	14	10
0	1	0	0	1	0	14	10
0	1	0	1	0	0	15	11
0	1	0	1	1	0	15	11
0	0	0	0	0	0	16	15
0	0	0	0	1	0	16	15
1	1	0	1	0	33.94632	17	16
1	1	0	1	1	14.17506	17	16
0	1	0	0	0	0	18	15
0	1	0	0	1	0	18	15
1	1	0	0	0	144.8989	19	15
1	1	0	0	1	7.319	19	15
0	1	0	1	0	49.17793	20	15
0	1	0	1	1	2.579268	20	15
0	0	0	1	0	31.01913	21	15
0	0	0	1	1	8.316889	21	15
1	1	0	0	0	0	22	10
1	1	0	0	1	0	22	10
0	0	0	0	0	26.65633	23	16
0	0	0	0	1	0	23	16
0	0	0	0	0	70.59344	24	15
0	0	0	0	1	23.96148	24	15
0	1	0	1	0	0	25	18
0	1	0	1	1	0	25	18
1	1	0	1	0	0	26	20
1	1	0	1	1	0	26	20
1	1	0	0	0	0	27	17
1	1	0	0	1	0	27	17
0	1	1	0	0	25.07012	28	17
0	1	1	0	1	28.73061	28	17
1	1	0	0	0	0	29	11
1	1	0	0	1	0	29	11
0	0	0	0	0	0	30	10
0	0	0	0	1	0	30	10
1	1	0	0	0	0	31	13
1	1	0	0	1	0	31	13
0	1	0	0	0	0	32	14
0	1	0	0	1	0	32	14
1	1	0	0	0	0	33	12
1	1	0	0	1	0	33	12
0	1	0	0	0	0	34	17
0	1	0	0	1	0	34	17
0	0	0	1	0	23.95128	35	20
0	0	0	1	1	5.731863	35	20
0	1	0	1	0	0	36	20
0	1	0	1	1	0	36	20
1	1	0	1	0	32.5347	37	8
1	1	0	1	1	13.97691	37	8
1	1	0	0	0	45.62077	38	8
1	1	0	0	1	13.64072	38	8
0	1	0	0	0	0	39	7
0	1	0	0	1	0	39	7
0	1	1	0	0	0	40	7
0	1	1	0	1	0	40	7
0	0	1	0	0	0	41	8
0	0	1	0	1	0	41	8
0	0	0	0	0	0	42	8
0	0	0	0	1	0	42	8
0	1	0	0	0	0	43	9
0	1	0	0	1	0	43	9
0	0	0	1	0	0	44	9
0	0	0	1	1	0	44	9
1	1	0	0	0	57.53611	45	4
1	1	0	0	1	29.1646	45	4
0	1	0	1	0	0	46	6
0	1	0	1	1	0	46	6
0	1	0	1	0	0	47	4
0	1	0	1	1	0	47	4
1	1	0	1	0	0	48	4
1	1	0	1	1	0	48	4
1	1	0	1	0	23.30293	49	4
1	1	0	1	1	0	49	4
1	0	0	1	0	20.78044	50	5
1	0	0	1	1	0	50	5
1	1	0	0	0	.8128695	51	4
1	1	0	0	1	0	51	4
0	0	0	1	0	0	52	4
0	0	0	1	1	0	52	4
1	1	0	0	0	0	53	2
1	1	0	0	1	0	53	2
0	0	0	1	0	12.78493	54	3
0	0	0	1	1	16.55898	54	3
0	1	0	0	0	.5542843	55	1
0	1	0	0	1	.0111068	55	1
0	0	0	1	0	9.894016	56	1
0	0	0	1	1	10.96016	56	1
0	1	1	0	0	2.538583	57	1
0	1	1	0	1	6.827503	57	1
1	1	0	1	0	0	58	1
1	1	0	1	1	0	58	1
0	0	1	0	0	8.549977	59	1
0	0	1	0	1	2.152292	59	1
1	1	0	1	0	52.01904	60	1
1	1	0	1	1	8.515899	60	1
1	1	0	1	0	0	61	2
1	1	0	1	1	0	61	2
0	1	0	0	0	28.41826	62	1
0	1	0	0	1	5.491279	62	1
1	1	1	0	0	0	63	2
1	1	1	0	1	0	63	2
0	1	0	0	0	3.104406	64	1
0	1	0	0	1	0	64	1
1	1	0	0	0	0	65	1
1	1	0	0	1	0	65	1
end

forvalues i = 1/20 {
	qui reghdfe y x1##x2##(x3 x4)##x5, absorb(fe) vce(cl clustervar)
	di `e(F)'
}

forvalues i = 1/20 {
	qui areg y x1##x2##(x3 x4)##x5, absorb(fe) vce(cl clustervar)
	di `e(F)'
}
```

**Comment by sergiocorreia** [comment] 2015-05-13 21:31
Whats the output of reghdfe, version ?

**Comment by NilsEnevoldsen** [comment] 2015-05-13 21:32
```stata
. reghdfe, version
2.1.47 12may2015

Dependencies installed?
- ivreg2            not
- avar              yes
- tuples            not
- parallel          not
```

**Comment by NilsEnevoldsen** [comment] 2015-05-13 21:33
I'll try with the GitHub bleeding edge.

**Comment by NilsEnevoldsen** [comment] 2015-05-13 21:34
No change with

```stata
. reghdfe, version
3.0.10 13may2015

Dependencies installed?
- ivreg2            not
- avar              yes
- tuples            not
```

**Comment by sergiocorreia** [comment] 2015-05-13 22:53
Hi Nils,

I hunted the bug a bit but I'm not sure how to proceed:

The problem lies behind -test- (which in turn calls the builtin _test)

What I did:

1) Run just the demeaning without the regression:
reghdfe y x1##x2##(x3 x4)##x5, absorb(fe) vce(cl clustervar, suite(default) ) tol(1e-8) savecache

2) Renamed and saved the resulting dta here:
https://github.com/sergiocorreia/reghdfe/blob/updated_mata/misc/fstat.dta

3) Ran this:
use fstat, clear
reg y x*, vce(cluster clustervar) nocons
testparm x*

Sometimes, test/testparm drops constant 2, and sometimes it drops constant 5. On the first case, you'll see Fstat=6.31, on the second (and more usual, occurs in 5/6 cases) you'll see 31.10

Why? I'm not sure at this stage (so far I've been using -test- as a means to avoid having to code the wald test by myself)

**Comment by NilsEnevoldsen** [comment] 2015-05-13 23:12
What does areg do?

**Comment by NilsEnevoldsen** [comment] 2015-05-13 23:16
Wait, there is no "x" in that dataset.

**Comment by NilsEnevoldsen** [comment] 2015-05-13 23:23
If I reg and test "x*", it always drops 5.

**Comment by sergiocorreia** [comment] 2015-05-13 23:23
Sorry, I meant `x*` (markdown replaced the two stars/asterisks)

What areg does is call _regress and _robust2 and somewhere in the middle compute the values

**Comment by NilsEnevoldsen** [comment] 2015-05-13 23:24
Oh, I need to reg again for it to sometimes drop constraint 2.

**Comment by sergiocorreia** [comment] 2015-05-13 23:24
```stata

. reg y x*, vce(cluster clustervar) nocons
[omitted]
. testparm x*

 ( 1)  x12 = 0
 ( 2)  x13 = 0
 ( 3)  x14 = 0
 ( 4)  x16 = 0
 ( 5)  x17 = 0
 ( 6)  x18 = 0
 ( 7)  x19 = 0
 ( 8)  x20 = 0
 ( 9)  x21 = 0
 (10)  x23 = 0
       Constraint 2 dropped

       F(  9,    19) =    6.31
            Prob > F =    0.0004
```

In most cases it drops 5, but at least on the Stata version I tested (v13.1) it dropped 2 a few cases

**Comment by sergiocorreia** [comment] 2015-05-13 23:35
I don't remember right now, but I had some pretty good reason for running -test- instead of just using the output of -regress-. In any case, the output of both -test- and the -regress- should coincide, so something is off.

Since this problem can be framed in terms of Statacorp regressions, one option may be to contact them; maybe they have more insight about what's going behind scenes in _test (I get it that sometimes you drop 2 and sometimes you drop 5, but if they are equivalent the results should be the same)

**Comment by NilsEnevoldsen** [comment] 2015-05-13 23:38
I think I might do that. The demeaned set of regressors seem to be well specified to my eye. Thanks for your help, Sergio.

**Comment by sergiocorreia** [comment] 2015-05-13 23:43
Let me know what they reply.

Best,
S

**Comment by NilsEnevoldsen** [comment] 2015-05-13 23:44
Of course.

**Comment by NilsEnevoldsen** [comment] 2015-05-13 23:50
Sorting by clustervar eliminates the instability, FWIW.

**Comment by sergiocorreia** [comment] 2015-05-14 00:02
Interesting.. I'm still wondering about what's the correct FStat in any case.

**Comment by NilsEnevoldsen** [comment] 2015-05-15 14:52
I got a beautiful response from StataCorp. TL;DR report a missing F statistic if r(drop) == 1. There is also r(dropped_[1,2,3,…]), which is probably unnecessary for this use case.

> Dear Nils,
> 
> For this model, it is not possible to perform a joint test that the
coefficients on all of the x variables are zero.  Both -regress- and
-testparm- inform you of this issue, but they have different ways of
handling the situation.
> 
> The -regress- command tries to test the 10 constraints jointly as an overall
model test. It would be misleading for us to report a test for 9 of the
coefficients as if it was a test for all 10.  Stata's estimation commands
report missing values for the overall model test in cases where it is not
possible to perform a joint test of coefficients being zero.  You can type
> 
>  help j_robustsingular
> 
> for more information on this.  
> 
> The -testparm- command, on the other hand, tests as many constraints as possible
and reports which constraint or constraints were dropped.  Because of finite
precision math, the algorithm that determines which constraint to drop may
occasionally choose different constraints. However, the note in the output
indicates which constraints are dropped, and the results that are reported
are a test of the remaining constraints.  You may not be interested in the
results from -testparm- when it is not possible to test all of the constraints
you requested.  If you are not looking at -testparm- output to see the note
about constraints that are omitted (say you are using -testparm- within a
larger program), you can check the returned scalar r(drop) to determine
whether any constraints were dropped before utilizing other results from the
-testparm- command.
> 
> I hope this helps.
> 
> Sincerely,
> 
> XXXXXX

**Comment by sergiocorreia** [comment] 2015-05-15 15:53
The problem of setting missing when r(drop)==1 is that it would lead to every regression with omitted variables to have a missing FStat.

One option may be to only give `test` the variables that were not missing in the `regress` step (i.e. without the o. prefix), and then check r(drop). In that case, we may i) set the F as missing, or ii) just give a warning in red. I need to think about it.. (specially because it touches not just the underlying regress, but the calls to ivreg2, ivregress, and multi-way-clustering)

**Comment by NilsEnevoldsen** [comment] 2015-05-15 16:03
Running -testparm- on non-omitted covariates seems like the right thing to do. The only reason to not set the F as missing would be if you also reported the dropped covariate(s), right? That could get out of hand, so it seems better to set it to missing. I don't know all the implications, though.

**Comment by sergiocorreia** [comment] 2015-05-26 18:52
This was partly fixed with c74bd5938cd76319a7da0b4b8c6773942b6dc208 so I'm closing the issue, but feel free to reopen it if needed.

For the record, what the commit does is:
- `test x1 x2 ...` will now exclude variables omitted in the `regress` stage.
- If `test` reports r(drop), a warning in red is given that the FStats are unreliable.
- I thought about either converting e(F) to missing or raising an error, but I need to think about it a bit more.
- For instance, are there cases where r(drop) occurs but the FStats are reliable, or can be made reliable?

**Closed by sergiocorreia** 2015-05-26 18:52 UTC

**Comment by NilsEnevoldsen** [comment] 2015-05-26 19:21
OK. How can I determine whether that warning was raised when I run reghdfe in non-interactive mode? I would like to replace the wrong F statistics myself in those cases.

It seems to me like the conservative thing to do is convert e(F) to missing, as a missing number is always preferable to a wrong one, but I'm sure you're thinking about this harder than I am.

**Comment by sergiocorreia** [comment] 2015-05-26 19:42
Ok just pushed a weird rebase that should fix the typo in the commit; hopefully I didn't mess up anyone's private repo.

About the Ftest thing.. yeah I agree a simple thing would be to set it as missing. Anyone that wants it later can just recover it with the -test- command.

Speaking of which, maybe we can replace the Wald test (what -test- uses) with a LR test..

http://support.sas.com/documentation/cdl/en/statug/63033/HTML/default/viewer.htm#statug_glimmix_a0000001435.htm

"The likelihood ratio test, on the other hand ... is computationally more demanding, but also provides the asymptotically more powerful and reliable test"

I already have all the inputs for a LR test, so I can just replace it or maybe add it as an alternative that will not suffer from the problems the Wald test has...

**Comment by sergiocorreia** [comment] 2015-05-26 20:06
Nevermind, LR tests are not compatible with robust SEs, so the Wald test will have to do...

**Comment by NilsEnevoldsen** [comment] 2015-06-09 19:21
I'd like to reopen this issue to keep it on your radar, since I think hasn't been resolved. If you declare it as "wontfix" I'll be happy to take that as a resolution, but in the meantime there are loose threads.

Specifically, your comments include:

> * I thought about either converting e(F) to missing or raising an error, but I need to think about it a bit more.
> * For instance, are there cases where r(drop) occurs but the FStats are reliable, or can be made reliable?
> * About the Ftest thing.. yeah I agree a simple thing would be to set it as missing. Anyone that wants it later can just recover it with the -test- command.

Again, IMHO, `areg` has the desirable behavior.

**Comment by NilsEnevoldsen** [comment] 2015-06-09 19:22
Oh wait, I just saw bf218f3. Whoops. Disregard. Time to update reghdfe.

**Comment by sergiocorreia** [comment] 2015-06-09 19:40
Github doesn't allow me to auto-close from commits unless the commit goes to the master branch, so yeah that leads to a bit of confusion.

Thus, I'm thinking about pushing dev-branch (v3) into master (v2), which also gives it more eyeballs. The only missing features are rewriting `hdfe.ado` and updating the help files, and then hopefully after a month or so it will be stable enough for SSC (It's gotten to the point that even minor improvements to the DoF computations lead to emails from authors/referees wondering why they can't perfectly replicate past regressions).

**Comment by NilsEnevoldsen** [comment] 2015-06-09 20:33
Indeed, bf218f3 seems lovely so far. Thank you!
