### ISSUE TITLE
Factor variables clash with residuals+iv

### ISSUE THREAD

**Issue by Danferno** [sergiocorreia/reghdfe#65] opened 2016-08-12 10:08 UTC
If the dependent variable is specified as a factor variable (e.g. D.var) and you opted to use the residuals option, you get the error message, "variable var not found" (r111).

**Comment by sergiocorreia** [comment] 2016-08-12 18:07
I can get `D.var` to work (it's more of a time series expression), but something like `42.turn` (a factor var. expression) is currently in the works:

https://github.com/sergiocorreia/reghdfe/issues/28

Note: the code for that has already been written but I need to finish a refactor which will take at the very least a couple of weeks

**Comment by sergiocorreia** [comment] 2016-08-12 18:10
Ok, I see what you are saying:

```stata
sysuse auto
bys turn: gen t = _n
xtset turn t
reghdfe D.price gear (turn=trunk), a(turn trunk t) residuals(y)
```

**Comment by sergiocorreia** [comment] 2016-08-12 18:19
Ok, it seems the bug is caused by this section:

```stata
if ("`residuals'"!="") {
    // ...
    `subpredict' double `residuals', `score'
}
```

This calls `ivreg2_p double y, resid`, which in turn runs `local lhs "`e(depvar)'"` and `tsrevar `lhs', substitute`. The content of e(depvar) is  `D.price` but the actual depvar on the dataset is `__D__price`.

The solution would involve setting `__D__price` as the depvar and then reverting it after the residuals are created.

I'll add the fix with the next release, but for now, you can try adding the option `reghdfe ... , ... ivsuite(ivregress)` which avoids this bug.

**Comment by Danferno** [comment] 2016-08-12 19:25
Cool, thanks! I ended up just creating D_var in advance, which also solves the problem.

**Comment by sergiocorreia** [comment] 2017-02-15 00:09
Closed as in the idea (hopefully) is that ivreg2 calls reghdfe and not the other way around

**Closed by sergiocorreia** 2017-02-15 00:09 UTC
Labels: bug
